name: build-and-deploy

on:
  push:
    branches: [ main ]
    
permissions:
  contents: write
  
jobs:
  deploy:
    runs-on: self-hosted

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t micro-ms-pedidos:${{ github.run_number }} msPedidos

    - name: Load image into Minikube
      run: minikube image load  micro-ms-pedidos:${{ github.run_number }}


    - name: Update Helm tag
      run: |
        (Get-Content helm-ms/values.yaml) -replace 'tag:.*', 'tag: ${{ github.run_number }}' | Set-Content helm-ms/values.yaml

    - name: Commit changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add helm-ms/values.yaml
        git commit -m "Se actualiza tag de imagen a ${{ github.run_number }}"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main

    - name: Deploy with Helm
      run: |
           helm upgrade --install micro-ms-pedidos ./helm-ms --set image.tag=${{ github.run_number }}
